# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7598c8d15a7f3bd1a80eac428d6abf7a7dcae8ba48789ff55cbfca3dc747c8af952e02a7573095b9550175656fc04108d87430de1cd8af38677614ad879ad17

test:
  secret_key_base: 4143d4d2b6b2f902316013479441b2ba5f92e8ed60369f5864d763d03e139f2192874d5e1ea7f9c6aa0d93943f2c528053aac42b8e23140385f3c0091de09d90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
